### PR TITLE
Fixes ObjectUnsubscribedError on prevSubject and nextSubject unsubscr…

### PR DESCRIPTION
**Pull request by msamprz**
Fixes ObjectUnsubscribedError on prevSubject and nextSubject unsubscribing

This issue arose on:

```
Angular CLI: 1.6.1
Node: 8.5.0
OS: win32 x64
Angular: 5.2.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.2.0
@angular/cli: 1.6.1
@angular/material: 5.2.0
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.1
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.6.2
webpack: 3.10.0
```

### CODE REVIEW

**Comment by bougarfaoui** [comment]
@msamprz  Thanks for the PR :)

**Comment by msamprz** [comment]
@bougarfaoui Thanks for the module, my dude :)

**Comment by sagarguhe** [comment]
I am not getting this change in my install.. what to do?

**Comment by msamprz** [comment]
@sagarguhe I believe @bougarfaoui hasn't pushed this code to npm. I found this out later in [another issue](https://github.com/bougarfaoui/ui-carousel/issues/7) in this repo. The solution is to use a different package, from a fork of this fix. I would have done it myself but I thought @bougarfaoui would push it to npm. Below you can find the package.

https://www.npmjs.com/package/ng-carousel-iuno
https://github.com/goergch/ui-carousel

```npm i ng-carousel-iuno```

**Comment by sagarguhe** [comment]
@msamprz thanks for the solution! I have installed your forked package using `npm i ng-carousel-iuno --save` it is installed correctly but when I try to import `UICarouselModule` from `ng-carousel-iuno` `ng-serve` throws this error: `ERROR in src/app/components/service-view/service-view.module.ts(7,34): error TS2307: Cannot find module 'ng-carousel-
iuno'`

**Comment by sagarguhe** [comment]
@msamprz never mind I installed the package again and it fixed the issue.. :) thanks for the fix :100:

**Comment by msamprz** [comment]
@sagarguhe no problem. Good luck!

**Comment by Muthukumaruma** [comment]
I updated the package but still I am facing the same issue

**Comment by msamprz** [comment]
Is your package the fork?

**Comment by Muthukumaruma** [comment]
hope no, I installed through npm

**Comment by msamprz** [comment]
From what I know and remember, this PR merge was not pushed to npm, so the fix is not implemented into the npm package. Try `npm i ng-carousel-iuno` this package.

**Pull request merged**
